


use std::{
    collections::{HashMap, HashSet},
    sync::{Arc, RwLock},
};

use dashmap::DashMap;
use typesize::TypeSize;

#[cfg(feature = "tiering_decoupled")]
use crossbeam_channel::{bounded as crossbeam_bounded, Receiver as CrossbeamReceiver, Sender as CrossbeamSender};
use crate::{
    HashedKey,
    //#[cfg(feature = "tiering_decoupled")]
    ObjectMapRef,
    object::{Object, ObjectSize},
};

use super::object::TieringObject;
#[cfg(feature = "hashtable_tiering")]
use super::object::TieringData;

use nohash_hasher::NoHashHasher;
use std::hash::BuildHasherDefault;


pub type NoHasher = BuildHasherDefault<NoHashHasher<HashedKey>>;

#[cfg(feature = "tiering_decoupled")]
const PROMOTION_QUEUE_BOUND: usize = 1024;
#[cfg(feature = "tiering_decoupled")]
const DEMOTION_QUEUE_BOUND: usize = 256;


pub use crate::{
	error::CacheError,
	policy::PaperPolicy,
}; 

use crate::PaperCache;

#[cfg(any(feature = "key_value_pmem", feature = "alloc_api_exp", feature = "global_hashtable_pmem", feature = "tiering_hashtable_pmem"))]
use crate::allocator::HybridObjects as Hybrid;

mod allocator_bindings {
    include!("../umf_allocator_bindings.rs"); // generated by bindgen
}

#[cfg(any(feature = "key_value_pmem", feature = "alloc_api_exp"))]
use hashbrown::HashMap as hashtable;



use std::sync::mpsc::{self, Sender, Receiver};
use std::sync::Mutex;
use std::thread::{self, JoinHandle};

#[cfg(feature = "sets_dram")]
#[derive(Debug, Clone)]
pub struct PmemBackfillJob<K> {
    pub key: K,
    pub hashed_key: HashedKey,
    pub value: Box<[u8]>,
    pub ttl: Option<u32>,
}


/// Configuration for the tiering manager
#[derive(Debug, Clone)]
pub struct TieringConfig {
    /// Threshold for DRAM usage in bytes
    /// When DRAM usage exceeds this threshold, cold objects are demoted from DRAM to PMEM
    pub dram_threshold: u64,

    /// High water mark as percentage of threshold (0.0 to 1.0)
    /// When DRAM usage exceeds threshold * high_water_mark, start demoting
    pub high_water_mark: f64,

    /// Low water mark as percentage of threshold (0.0 to 1.0)
    /// Continue demoting until DRAM usage falls below threshold * low_water_mark
    pub low_water_mark: f64,

    /// Hotness threshold: minimum access count before promotion
    pub hotness_threshold: u64,

    /// Whether to place the tiering manager's hashtable in persistent memory
    /// When true, the dram_cache hashtable uses pmem allocator
    /// When false, uses default DRAM allocation
    pub use_pmem_for_tiering_hashtable: bool,

    /// Adaptive tiering: size (bytes) under which objects get an aggressive promotion bias
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub small_object_cutoff: u64,

    /// Adaptive tiering: recency window (ms) that grants an extra promotion bias
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub recency_boost_ms: u64,

    /// Adaptive tiering: additional access count required when DRAM is under pressure
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub pressure_penalty: u64,

    /// Adaptive tiering: additional access bias when DRAM has ample headroom
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub headroom_bonus: u64,

    /// Adaptive tiering: EWMA smoothing factor (0,1]; higher reacts faster
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub adaptive_alpha: f64,

    /// Adaptive tiering: minimum/maximum clamp for dynamic small-object cutoff
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub small_cutoff_min: u64,
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub small_cutoff_max: u64,

    /// Adaptive tiering: floor/ceiling for dynamic hotness threshold
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub hotness_floor: u64,
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub hotness_ceiling: u64,

    #[cfg(feature = "hashtable_tiering")]
    /// Warm threshold: minimum access count for pointer-only promotion (hashtable_tiering feature)
    /// Objects reaching this threshold get metadata in DRAM but data stays in CXL
    pub warm_threshold: u64,

    #[cfg(feature = "hashtable_tiering")]
    /// Hot threshold: minimum access count for full data copy promotion (hashtable_tiering feature)
    /// Objects reaching this threshold get a full physical copy in DRAM
    pub hot_threshold: u64,
}

impl Default for TieringConfig {
    fn default() -> Self {
        TieringConfig {
            dram_threshold: 1 * 1024 * 1024 * 1024, // 1 GB default
            high_water_mark: 0.95,
            low_water_mark: 0.7,
            hotness_threshold: 3, // Promote after 3 accesses
            use_pmem_for_tiering_hashtable: false, // Default to DRAM
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            small_object_cutoff: 8 * 1024, // 8 KiB favors tiny objects for DRAM
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            recency_boost_ms: 500, // sub-second recency bump
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            pressure_penalty: 1, // raise threshold when DRAM is hot
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            headroom_bonus: 1, // lower threshold when DRAM is cold
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            adaptive_alpha: 0.2,
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            small_cutoff_min: 1024,
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            small_cutoff_max: 512 * 1024,
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            hotness_floor: 1,
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            hotness_ceiling: 8,
            #[cfg(feature = "hashtable_tiering")]
            warm_threshold: 2, // Pointer promotion after 2 accesses
            #[cfg(feature = "hashtable_tiering")]
            hot_threshold: 5, // Physical copy after 5 accesses
        }
    }
}

/// Statistics for the tiering manager
#[derive(Debug, Clone, Default)]
pub struct TieringStats {
    /// Number of objects currently in DRAM
    pub dram_objects: u64,

    /// Total size of objects in DRAM (bytes)
    pub dram_size: u64,

    /// Total size of warm (pointer-only) objects in DRAM (bytes)
    pub pointer_size: u64,

    /// Number of promotions from PMEM to DRAM
    pub promotions: u64,

    /// Number of demotions from DRAM to PMEM
    pub demotions: u64,

    /// Number of objects only in PMEM
    pub pmem_only_objects: u64,

    pub pointer_promotions: u64, // For hashtable_tiering feature


    pub pointer_demotions: u64, // For hashtable_tiering feature

    pub warm_objects: u64, // For hashtable_tiering feature

    pub hot_objects: u64, // For hashtable_tiering feature

    pub dram_only_objects: u64, // For sets_dram feature
}

/// Tier location for an object
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    /// Object exists in both DRAM (copy) and PMEM (source of truth)
    DramAndPmem,

    /// Object exists only in PMEM
    PmemOnly,

    #[cfg(feature = "hashtable_tiering")]
    /// Object has metadata/pointer in DRAM but data remains in PMEM (hashtable_tiering feature)
    /// This is the "Warm" tier - metadata access is fast but data is still in CXL
    DramPtrToPmem,

    #[cfg(feature = "sets_dram")]
    /// Object exists only in DRAM (sets_dram feature)
    DramOnly,
}

/// Information about an object's tiering status
#[derive(Debug, Clone)]
struct ObjectTierInfo {
    /// Current tier location
    tier: Tier,

    /// Size of the object in bytes
    size: ObjectSize,

    /// Estimated DRAM footprint for pointer-only tiering
    pointer_size: u64,

    /// Access count (for LFU-like promotion/demotion)
    access_count: u64,

    /// Last access timestamp (for LRU-like promotion/demotion)
    last_access: std::time::Instant,
}

/// Tiering Manager
/// 
/// Manages object placement between DRAM and PMEM tiers.
/// DRAM contains hot COPIES of objects while PMEM is the source of truth.
/// 
/// ## Data Copy Model
/// Hot objects are physically copied to a DRAM cache for fast access.
/// The PMEM tier always contains all objects (source of truth).
/// DRAM tier contains copies of frequently accessed objects.
/// 
/// ## Promotion Policy
/// Objects are promoted to DRAM after being accessed more than the configured threshold.
/// This simple heuristic ensures that only objects with repeated access are promoted.
pub struct TieringManager<K, V> {
    config: Arc<RwLock<TieringConfig>>,
    stats: Arc<RwLock<TieringStats>>,

    /// Tracking information for each object
    object_info: Arc<RwLock<HashMap<HashedKey, ObjectTierInfo>>>,

    /// Set of objects currently in DRAM (for fast lookup)
    dram_objects: Arc<RwLock<HashSet<HashedKey>>>,
    
    /// DRAM cache storing TieringObject<K> instances
    /// TieringObject always uses DRAM allocation (not Hybrid allocator) to ensure
    /// both key and value are in DRAM for fast access to hot objects
    #[cfg(all(feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    dram_cache: Arc<DashMap<HashedKey, TieringObject<K>, NoHasher>>,
    
    #[cfg(all(feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem"), feature = "hashtable_tiering"))]
    dram_cache: Arc<DashMap<HashedKey, TieringObject<K, V>, NoHasher>>,
    
    #[cfg(all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K>, BuildHasherDefault<NoHashHasher<u64>>, Hybrid>>>,
    
    #[cfg(all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", feature = "hashtable_tiering"))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K, V>, BuildHasherDefault<NoHashHasher<u64>>, Hybrid>>>,
    
    #[cfg(all(feature = "alloc_api_exp", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K>, BuildHasherDefault<NoHashHasher<u64>>>>>,
    
    #[cfg(all(feature = "alloc_api_exp", not(feature = "tiering_hashtable_pmem"), feature = "hashtable_tiering"))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K, V>, BuildHasherDefault<NoHashHasher<u64>>>>>,
    
    #[cfg(all(feature = "alloc_api_exp", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K>, BuildHasherDefault<NoHashHasher<u64>>, Hybrid>>>,
    
    #[cfg(all(feature = "alloc_api_exp", feature = "tiering_hashtable_pmem", feature = "hashtable_tiering"))]
    dram_cache: Arc<RwLock<hashtable<HashedKey, TieringObject<K, V>, BuildHasherDefault<NoHashHasher<u64>>, Hybrid>>>,
    

    #[cfg(feature = "sets_dram")]
    pmem_tx: Sender<HashedKey>,
    #[cfg(feature = "sets_dram")]
    _pmem_consumer: JoinHandle<()>,
    /// Pending backfill jobs indexed by hashed key.
    /// Acts as the source of truth for unprocessed jobs; the channel carries
    /// only the key so jobs can be claimed either by the background consumer
    /// or by force_sync_persist without double-processing.
    #[cfg(feature = "sets_dram")]
    pending_jobs: Arc<Mutex<HashMap<HashedKey, PmemBackfillJob<K>>>>,
    /// Stored reference to the batch-persist closure so that
    /// force_sync_persist can call it synchronously from any thread.
    #[cfg(feature = "sets_dram")]
    sync_persist_fn: Arc<dyn Fn(Vec<PmemBackfillJob<K>>) + Send + Sync>,

    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    ewma_obj_size: Arc<RwLock<f64>>,
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    ewma_hotness: Arc<RwLock<f64>>,

    _phantom: std::marker::PhantomData<(K, V)>,
}

impl<K, V> TieringManager<K, V>
where
    K: TypeSize + Clone,
    V: TypeSize + Clone,
{
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    fn ewma_update(current: f64, sample: f64, alpha: f64) -> f64 {
        if current == 0.0 {
            sample
        } else {
            (1.0 - alpha) * current + alpha * sample
        }
    }

    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    fn adaptive_small_cutoff(&self, config: &TieringConfig) -> u64 {
        let avg = *self.ewma_obj_size.read().unwrap();
        let cutoff = avg.round() as u64;
        cutoff.clamp(config.small_cutoff_min, config.small_cutoff_max)
    }

    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    fn adaptive_hotness_base(&self, access_sample: f64, config: &TieringConfig) -> u64 {
        let mut ewma = self.ewma_hotness.write().unwrap();
        let updated = Self::ewma_update(*ewma, access_sample, config.adaptive_alpha);
        *ewma = updated;
        let base = updated.round() as u64;
        base.clamp(config.hotness_floor, config.hotness_ceiling)
    }

    #[inline]
    fn combined_usage(stats: &TieringStats) -> u64 {
        stats.dram_size.saturating_add(stats.pointer_size)
    }

    #[cfg(feature = "tiering_decoupled")]
    pub fn spawn_data_plane(
        manager: Arc<TieringManager<K, V>>,
        objects: ObjectMapRef<K, V>,
    ) -> (CrossbeamSender<HashedKey>, CrossbeamSender<Vec<HashedKey>>)
    where
        K: 'static + Eq + TypeSize + Clone + Send + Sync,
        V: 'static + TypeSize + Clone + AsRef<[u8]> + Send + Sync,
    {
        let (promotion_tx, promotion_rx) = crossbeam_bounded(PROMOTION_QUEUE_BOUND);
        let (demotion_tx, demotion_rx) = crossbeam_bounded(DEMOTION_QUEUE_BOUND);

        Self::spawn_promoter(manager.clone(), objects, promotion_rx);
        Self::spawn_demoter(manager, demotion_rx);

        (promotion_tx, demotion_tx)
    }

    #[cfg(feature = "tiering_decoupled")]
    fn spawn_promoter(
        manager: Arc<TieringManager<K, V>>,
        objects: ObjectMapRef<K, V>,
        promotion_rx: CrossbeamReceiver<HashedKey>,
    )
    where
        K: 'static + Eq + TypeSize + Clone + Send + Sync,
        V: 'static + TypeSize + Clone + AsRef<[u8]> + Send + Sync,
    {
        thread::Builder::new()
            .name("tiering-promoter".into())
            .spawn(move || {
                while let Ok(key) = promotion_rx.recv() {
                    #[cfg(not(feature = "global_hashtable_pmem"))]
                    {
                        if let Some(object_ref) = objects.get(&key) {
                            let _ = manager.promote_to_dram_with_object(key, &*object_ref);
                        }
                    }

                    #[cfg(feature = "global_hashtable_pmem")]
                    {
                        if let Some(object_ref) = objects.read().unwrap().get(&key) {
                            let _ = manager.promote_to_dram_with_object(key, object_ref);
                        }
                    }
                }
            })
            .expect("failed to spawn tiering-promoter thread");
    }

    #[cfg(feature = "tiering_decoupled")]
    fn spawn_demoter(
        manager: Arc<TieringManager<K, V>>,
        demotion_rx: CrossbeamReceiver<Vec<HashedKey>>,
    )
    where
        K: 'static + Eq + TypeSize + Clone + Send + Sync,
        V: 'static + TypeSize + Clone + AsRef<[u8]> + Send + Sync,
    {
        thread::Builder::new()
            .name("tiering-demoter".into())
            .spawn(move || {
                while let Ok(batch) = demotion_rx.recv() {
                    for key in batch {
                        #[cfg(feature = "sets_dram")]
                        if manager.is_dram_only(key) {
                            manager.force_sync_persist(key);
                        }

                        let _ = manager.demote_from_dram(key);
                    }
                }
            })
            .expect("failed to spawn tiering-demoter thread");
    }

    #[cfg(feature = "hashtable_tiering")]
    #[inline]
    fn pointer_footprint(&self, object: &Object<K, V>) -> u64 {
        let key_bytes = object.key().get_size() as u64;
        let data_ptr_bytes = std::mem::size_of::<TieringData<V>>() as u64;
        let expiry_bytes = std::mem::size_of::<crate::object::ExpireTime>() as u64;
        key_bytes + data_ptr_bytes + expiry_bytes
    }

    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    #[inline]
    fn dram_pressure(&self, stats: &TieringStats, config: &TieringConfig) -> f64 {
        if config.dram_threshold == 0 {
            1.0
        } else {
            Self::combined_usage(stats) as f64 / config.dram_threshold as f64
        }
    }

    #[cfg(all(test, any(feature = "adaptive_tiering", feature = "adaptive")))]
    fn debug_adaptive_cutoffs(&self) -> (u64, u64) {
        let config = self.config.read().unwrap();
        let small = self.adaptive_small_cutoff(&config);
        let hot = {
            let ew = *self.ewma_hotness.read().unwrap();
            let base = ew.round() as u64;
            base.clamp(config.hotness_floor, config.hotness_ceiling)
        };
        (small, hot)
    }

    /// Creates a new TieringManager with the given configuration.
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem")))]
    pub fn new(config: TieringConfig) -> Self {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        #[cfg(feature = "sets_dram")]
        let (dummy_tx, dummy_rx) = mpsc::channel::<HashedKey>();
        #[cfg(feature = "sets_dram")]
        drop(dummy_rx);
        #[cfg(feature = "sets_dram")]
        let dummy_handle = thread::spawn(|| {});

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(DashMap::with_hasher(NoHasher::default())),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            #[cfg(feature = "sets_dram")]
            pmem_tx: dummy_tx,
            #[cfg(feature = "sets_dram")]
            _pmem_consumer: dummy_handle,
            #[cfg(feature = "sets_dram")]
            pending_jobs: Arc::new(Mutex::new(HashMap::new())),
            #[cfg(feature = "sets_dram")]
            sync_persist_fn: Arc::new(|_batch| {}),
            _phantom: std::marker::PhantomData,
        }
    }

    /// Creates a new TieringManager for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Both the object key and value are PMEM-resident in the main cache.
    /// Promotion reads the key from PMEM (via `Box<K, Hybrid>`) and copies
    /// both key and value bytes into a DRAM-resident `TieringObject<K>`.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    pub fn new(config: TieringConfig) -> Self {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        #[cfg(feature = "sets_dram")]
        let (dummy_tx, dummy_rx) = mpsc::channel::<HashedKey>();
        #[cfg(feature = "sets_dram")]
        drop(dummy_rx);
        #[cfg(feature = "sets_dram")]
        let dummy_handle = thread::spawn(|| {});

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(DashMap::with_hasher(NoHasher::default())),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            #[cfg(feature = "sets_dram")]
            pmem_tx: dummy_tx,
            #[cfg(feature = "sets_dram")]
            _pmem_consumer: dummy_handle,
            #[cfg(feature = "sets_dram")]
            pending_jobs: Arc::new(Mutex::new(HashMap::new())),
            #[cfg(feature = "sets_dram")]
            sync_persist_fn: Arc::new(|_batch| {}),
            _phantom: std::marker::PhantomData,
        }
    }

    #[cfg(all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem"))]
    pub fn new(config: TieringConfig) -> Self {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        #[cfg(feature = "sets_dram")]
        let (dummy_tx, dummy_rx) = mpsc::channel::<HashedKey>();
        #[cfg(feature = "sets_dram")]
        drop(dummy_rx);
        #[cfg(feature = "sets_dram")]
        let dummy_handle = thread::spawn(|| {});

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher_in(NoHasher::default(), Hybrid))),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            #[cfg(feature = "sets_dram")]
            pmem_tx: dummy_tx,
            #[cfg(feature = "sets_dram")]
            _pmem_consumer: dummy_handle,
            #[cfg(feature = "sets_dram")]
            pending_jobs: Arc::new(Mutex::new(HashMap::new())),
            #[cfg(feature = "sets_dram")]
            sync_persist_fn: Arc::new(|_batch| {}),
            _phantom: std::marker::PhantomData,
        }
    }

    #[cfg(all(feature = "alloc_api_exp", not(feature = "tiering_hashtable_pmem")))]
    pub fn new(config: TieringConfig) -> Self {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        #[cfg(feature = "sets_dram")]
        let (dummy_tx, dummy_rx) = mpsc::channel::<HashedKey>();
        #[cfg(feature = "sets_dram")]
        drop(dummy_rx);
        #[cfg(feature = "sets_dram")]
        let dummy_handle = thread::spawn(|| {});

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher(NoHasher::default()))),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            #[cfg(feature = "sets_dram")]
            pmem_tx: dummy_tx,
            #[cfg(feature = "sets_dram")]
            _pmem_consumer: dummy_handle,
            #[cfg(feature = "sets_dram")]
            pending_jobs: Arc::new(Mutex::new(HashMap::new())),
            #[cfg(feature = "sets_dram")]
            sync_persist_fn: Arc::new(|_batch| {}),
            _phantom: std::marker::PhantomData,
        }
    }

    #[cfg(all(feature = "alloc_api_exp", feature = "tiering_hashtable_pmem"))]
    pub fn new(config: TieringConfig) -> Self {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        #[cfg(feature = "sets_dram")]
        let (dummy_tx, dummy_rx) = mpsc::channel::<HashedKey>();
        #[cfg(feature = "sets_dram")]
        drop(dummy_rx);
        #[cfg(feature = "sets_dram")]
        let dummy_handle = thread::spawn(|| {});

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher_in(NoHasher::default(), Hybrid))),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            #[cfg(feature = "sets_dram")]
            pmem_tx: dummy_tx,
            #[cfg(feature = "sets_dram")]
            _pmem_consumer: dummy_handle,
            #[cfg(feature = "sets_dram")]
            pending_jobs: Arc::new(Mutex::new(HashMap::new())),
            #[cfg(feature = "sets_dram")]
            sync_persist_fn: Arc::new(|_batch| {}),
            _phantom: std::marker::PhantomData,
        }
    }

    /// Creates a new TieringManager with default configuration
    pub fn with_defaults() -> Self {
        Self::new(TieringConfig::default())
    }

    /// Registers a new object in PMEM
    #[cfg(not(feature = "sets_dram"))]
    pub fn register_object(&self, key: HashedKey, size: ObjectSize) {
        let mut info_map = self.object_info.write().unwrap();

        info_map.insert(key, ObjectTierInfo {
            tier: Tier::PmemOnly,
            size,
            pointer_size: 0,
            access_count: 0,
            last_access: std::time::Instant::now(),
        });

        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        {
            let alpha = self.config.read().unwrap().adaptive_alpha;
            let mut ewma = self.ewma_obj_size.write().unwrap();
            *ewma = Self::ewma_update(*ewma, size as f64, alpha);
        }

        let mut stats = self.stats.write().unwrap();
        stats.pmem_only_objects += 1;
    }

    #[cfg(feature = "sets_dram")]
    pub fn register_object(&self, key: HashedKey, size: ObjectSize) {
        let mut info_map = self.object_info.write().unwrap();

        info_map.insert(key, ObjectTierInfo {
            tier: Tier::DramOnly,
            size,
            pointer_size: 0,
            access_count: 0,
            last_access: std::time::Instant::now(),
        });

        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        {
            let alpha = self.config.read().unwrap().adaptive_alpha;
            let mut ewma = self.ewma_obj_size.write().unwrap();
            *ewma = Self::ewma_update(*ewma, size as f64, alpha);
        }

        let mut stats = self.stats.write().unwrap();
        stats.dram_only_objects += 1;
    }

    //let paper_cache_for_bg = paper_cache.clone(); // Arc<PaperCache<...>>
    
    //let tiering = TieringManager::new_with_backfill(config, move |job| {
        // IMPORTANT: call a PMEM-only path to avoid recursion into set_dram
        // Example:
        // let _ = paper_cache_for_bg.set_pmem_only(job.key, &job.value, job.ttl);
    //});
    // ...existing code...

    /// Spawns the background PMEM consumer thread.
    /// Drains the channel in batches and calls persist_fn once per batch,
    /// using pending_jobs as a claim registry to avoid double-processing
    /// jobs that were already force-persisted synchronously.
    #[cfg(feature = "sets_dram")]
    fn spawn_pmem_consumer<F>(
        rx: Receiver<HashedKey>,
        pending_jobs: Arc<Mutex<HashMap<HashedKey, PmemBackfillJob<K>>>>,
        persist_fn: F,
    ) -> JoinHandle<()>
    where
        K: Send + 'static,
        F: Fn(Vec<PmemBackfillJob<K>>) + Send + 'static,
    {
        thread::spawn(move || {
            loop {
                // Block until at least one key is available.
                let Ok(first_key) = rx.recv() else { break };

                // Drain any additional keys that are already queued.
                let mut keys = vec![first_key];
                while let Ok(key) = rx.try_recv() {
                    keys.push(key);
                }

                // Claim jobs from pending_jobs; skip keys already handled by
                // force_sync_persist (they were removed from the map first).
                let mut batch = Vec::with_capacity(keys.len());
                {
                    let mut pending = pending_jobs.lock()
                        .expect("pending_jobs mutex should not be poisoned");
                    for key in keys {
                        if let Some(job) = pending.remove(&key) {
                            batch.push(job);
                        }
                    }
                }

                if !batch.is_empty() {
                    persist_fn(batch);
                }
            }
        })
    }
    
    
    #[cfg(all(feature = "sets_dram", feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    pub fn new_with_backfill<F>(config: TieringConfig, persist_fn: F) -> Self
    where
        K: Send + 'static,
        F: Fn(Vec<PmemBackfillJob<K>>) + Send + Sync + 'static,
    {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        let pending_jobs: Arc<Mutex<HashMap<HashedKey, PmemBackfillJob<K>>>> =
            Arc::new(Mutex::new(HashMap::new()));
        let sync_fn: Arc<dyn Fn(Vec<PmemBackfillJob<K>>) + Send + Sync> = Arc::new(persist_fn);

        let (tx, rx) = mpsc::channel::<HashedKey>();
        let handle = Self::spawn_pmem_consumer(rx, pending_jobs.clone(), {
            let sync_fn = sync_fn.clone();
            move |batch| sync_fn(batch)
        });

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(DashMap::with_hasher(NoHasher::default())),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            pmem_tx: tx,
            _pmem_consumer: handle,
            pending_jobs,
            sync_persist_fn: sync_fn,
            _phantom: std::marker::PhantomData,
        }
    }

    #[cfg(all(feature = "sets_dram", feature = "key_value_pmem", feature = "tiering_hashtable_pmem"))]
    pub fn new_with_backfill<F>(config: TieringConfig, persist_fn: F) -> Self
    where
        K: Send + 'static,
        F: Fn(Vec<PmemBackfillJob<K>>) + Send + Sync + 'static,
    {
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_obj_init = config.small_object_cutoff as f64;
        #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
        let ewma_hot_init = config.hotness_threshold as f64;

        let pending_jobs: Arc<Mutex<HashMap<HashedKey, PmemBackfillJob<K>>>> =
            Arc::new(Mutex::new(HashMap::new()));
        let sync_fn: Arc<dyn Fn(Vec<PmemBackfillJob<K>>) + Send + Sync> = Arc::new(persist_fn);

        let (tx, rx) = mpsc::channel::<HashedKey>();
        let handle = Self::spawn_pmem_consumer(rx, pending_jobs.clone(), {
            let sync_fn = sync_fn.clone();
            move |batch| sync_fn(batch)
        });

        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())),
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher_in(NoHasher::default(), Hybrid))),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_obj_size: Arc::new(RwLock::new(ewma_obj_init)),
            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            ewma_hotness: Arc::new(RwLock::new(ewma_hot_init)),
            pmem_tx: tx,
            _pmem_consumer: handle,
            pending_jobs,
            sync_persist_fn: sync_fn,
            _phantom: std::marker::PhantomData,
        }
    }

    #[cfg(feature = "sets_dram")]
    pub fn set_dram(&self, hashed_key: HashedKey, key: K, value: &[u8], ttl: Option<u32>) {
        // fast metadata path
        {
            let mut info_map = self.object_info.write().unwrap();
            let size = value.len() as ObjectSize;
            info_map.insert(hashed_key, ObjectTierInfo {
                tier: Tier::DramOnly,
                size,
                pointer_size: 0,
                access_count: 0,
                last_access: std::time::Instant::now(),
            });
        }
        self.dram_objects.write().unwrap().insert(hashed_key);

        // Build the job and register it in pending_jobs before notifying the
        // consumer thread so that the job is always retrievable via
        // force_sync_persist even if the consumer wakes up immediately.
        let job = PmemBackfillJob {
            key,
            hashed_key,
            value: value.to_vec().into_boxed_slice(),
            ttl,
        };
        self.pending_jobs
            .lock()
            .expect("pending_jobs mutex should not be poisoned")
            .insert(hashed_key, job);
        let _ = self.pmem_tx.send(hashed_key);
    }

    /// Called by the background PMEM writer after successfully persisting an object.
    /// Transitions the object's tier from `DramOnly` to `DramAndPmem`.
    #[cfg(feature = "sets_dram")]
    pub fn mark_persisted(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();
        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramOnly {
                info.tier = Tier::DramAndPmem;
                let mut stats = self.stats.write().unwrap();
                stats.dram_only_objects = stats.dram_only_objects.saturating_sub(1);
                stats.dram_objects = stats.dram_objects.saturating_add(1);
            }
        }
    }

    /// Records an access to an object
    /// Returns true if the object should be promoted to DRAM
    /// 
    /// ## Promotion Heuristic
    /// Objects are promoted after reaching the configured hotness threshold.
    #[cfg(not(feature = "hashtable_tiering"))]
    pub fn record_access(&self, key: HashedKey) -> bool {
        let config = self.config.read().unwrap();
        let hotness_threshold = config.hotness_threshold;
        drop(config);

        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            info.access_count += 1;
            info.last_access = std::time::Instant::now();

            // Decide if promotion is needed

            //umf_allocator_bindings::check_tier();

            match info.tier {
                Tier::PmemOnly => {
                    // Check if we should promote based on access count
                    info.access_count >= hotness_threshold
                }
                Tier::DramAndPmem => {
                    // Already in DRAM
                    false
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Already in DRAM-only tier
                    false
                }
            }
        } else {
            false
        }
    }

    /// Adaptive access recording that dynamically adjusts the promotion
    /// threshold based on DRAM pressure, object size, and short-term recency.
    /// Favors tiny or bursty-hot objects when there is headroom, and raises the
    /// bar when DRAM is near capacity to avoid flooding it with lukewarm keys.
    #[cfg(all(any(feature = "adaptive_tiering", feature = "adaptive"), not(feature = "hashtable_tiering")))]
    pub fn record_access_adaptive(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            let prev_access = info.last_access;
            let now = std::time::Instant::now();
            info.access_count += 1;
            info.last_access = now;

            // Never promote on the very first access; we only use it to seed
            // recency/size tracking so adaptive thresholds still require a
            // second touch before promotion.
            if info.access_count == 1 {
                return false;
            }

            let config = self.config.read().unwrap();
            let stats = self.stats.read().unwrap();
            let pressure = self.dram_pressure(&stats, &config);
            drop(stats);

            let small_cutoff = self.adaptive_small_cutoff(&config);
            let mut effective = self.adaptive_hotness_base(info.access_count as f64, &config);

            if pressure > config.high_water_mark {
                effective = effective.saturating_add(config.pressure_penalty);
            } else if pressure < config.low_water_mark {
                effective = effective.saturating_sub(config.headroom_bonus);
            }

            if info.size as u64 <= small_cutoff {
                effective = effective.saturating_sub(1);
            }

            let age_ms = now.duration_since(prev_access).as_millis() as u64;
            if age_ms <= config.recency_boost_ms {
                effective = effective.saturating_sub(1);
            }

            effective = effective.clamp(config.hotness_floor, config.hotness_ceiling);
            if effective == 0 {
                effective = 1;
            }

            match info.tier {
                Tier::PmemOnly => info.access_count >= effective,
                Tier::DramAndPmem => false,
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => false,
            }
        } else {
            false
        }
    }

    /// Hashtable-tiering builds reuse the adaptive thresholds computed inside
    /// `record_access` (warm/hot promotion). Provide a feature-compatible
    /// entrypoint so call sites gated on `adaptive` continue to compile.
    #[cfg(all(any(feature = "adaptive_tiering", feature = "adaptive"), feature = "hashtable_tiering"))]
    pub fn record_access_adaptive(&self, key: HashedKey) -> bool {
        self.record_access(key)
    }

    #[cfg(feature = "hashtable_tiering")]
    /// Records an access to an object (hashtable_tiering version)
    /// Returns true if the object should be promoted to DRAM (physical copy or pointer)
    /// 
    /// ## Promotion Heuristic (hashtable_tiering)
    /// Objects are promoted in two stages:
    /// 1. Warm tier (pointer-only): After warm_threshold accesses
    /// 2. Hot tier (physical copy): After hot_threshold accesses
    pub fn record_access(&self, key: HashedKey) -> bool {
        let config = self.config.read().unwrap();
        let warm_threshold = config.warm_threshold;
        let hot_threshold = config.hot_threshold;
        drop(config);

        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            info.access_count += 1;
            let prev_access = info.last_access;
            info.last_access = std::time::Instant::now();

            #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
            let (warm_threshold, hot_threshold) = {
                let config = self.config.read().unwrap();
                let stats = self.stats.read().unwrap();
                let pressure = self.dram_pressure(&stats, &config);
                drop(stats);

                let small_cutoff = self.adaptive_small_cutoff(&config);
                let mut warm = self.adaptive_hotness_base(info.access_count as f64, &config);
                let mut hot_gap = config.hot_threshold.saturating_sub(config.warm_threshold);
                if hot_gap == 0 {
                    hot_gap = 1;
                }
                let mut hot = warm.saturating_add(hot_gap);

                if pressure > config.high_water_mark {
                    warm = warm.saturating_add(config.pressure_penalty);
                    hot = hot.saturating_add(config.pressure_penalty);
                } else if pressure < config.low_water_mark {
                    warm = warm.saturating_sub(config.headroom_bonus);
                    hot = hot.saturating_sub(config.headroom_bonus);
                }

                if info.size as u64 <= small_cutoff {
                    warm = warm.saturating_sub(1);
                }

                let age_ms = info.last_access.duration_since(prev_access).as_millis() as u64;
                if age_ms <= config.recency_boost_ms {
                    warm = warm.saturating_sub(1);
                }

                warm = warm.clamp(config.hotness_floor, config.hotness_ceiling);
                hot = hot.max(warm.saturating_add(1));
                hot = hot.clamp(config.hotness_floor.max(warm + 1), config.hotness_ceiling);

                (warm, hot)
            };

            // Decide if promotion is needed
            match info.tier {
                Tier::PmemOnly => {
                    // Check if we should promote to warm tier (pointer-only)
                    info.access_count >= warm_threshold
                }
                Tier::DramPtrToPmem => {
                    // Check if we should promote to hot tier (physical copy)
                    info.access_count >= hot_threshold
                }
                Tier::DramAndPmem => {
                    // Already in hot tier
                    false
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Already in DRAM-only tier
                    false
                }
            }
        } else {
            false
        }
    }

    /// Helper method to create a TieringObject with physically copied data
    /// Extracts bytes from source object and creates a new TieringObject
    #[cfg(not(feature = "hashtable_tiering"))]
    fn create_dram_object(&self, object: &Object<K, V>) -> TieringObject<K>
    where
        K: Clone,
        V: AsRef<[u8]>,
    {
        // Extract bytes from source (which may be PMEM-allocated)
        let source_data = object.data();
        // First .as_ref() dereferences Arc<V> -> &V
        // Second .as_ref() calls AsRef<[u8]> trait on V -> &[u8]
        let bytes: &[u8] = source_data.as_ref().as_ref();
        
        // Create new DRAM-allocated Box<[u8]> (physical copy)
        let dram_data: Box<[u8]> = bytes.to_vec().into_boxed_slice();
        
        // Create new TieringObject with key, data, and expiry
        TieringObject::with_expiry(object.key().clone(), dram_data, object.expiry())
    }

    #[cfg(feature = "hashtable_tiering")]
    /// Helper method to create a TieringObject with physically copied data (hashtable_tiering version)
    fn create_dram_object(&self, object: &Object<K, V>) -> TieringObject<K, V>
    where
        K: Clone,
        V: AsRef<[u8]>,
    {
        // Extract bytes from source (which may be PMEM-allocated)
        let source_data = object.data();
        // First .as_ref() dereferences Arc<V> -> &V
        // Second .as_ref() calls AsRef<[u8]> trait on V -> &[u8]
        let bytes: &[u8] = source_data.as_ref().as_ref();
        
        // Create new DRAM-allocated Box<[u8]> (physical copy)
        let dram_data: Box<[u8]> = bytes.to_vec().into_boxed_slice();
        
        // Create new TieringObject with key, data, and expiry
        TieringObject::with_expiry(object.key().clone(), dram_data, object.expiry())
    }

    #[cfg(feature = "hashtable_tiering")]
    /// Helper method to create a TieringObject with CXL reference (zero-copy)
    fn create_warm_object(&self, object: &Object<K, V>) -> TieringObject<K, V>
    where
        K: Clone,
    {
        // Create TieringObject with pointer to CXL data (zero-copy)
        TieringObject::with_cxl_reference(
            object.key().clone(),
            object.data(),
            object.expiry()
        )
    }

    /// Promotes an object to DRAM by creating a physical copy with DRAM-allocated data.
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    // Create DRAM object with physical data copy
                    let dram_object = self.create_dram_object(object);
                    
                    // Store the TieringObject in the DRAM cache
                    self.dram_cache.insert(key, dram_object);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }

    /// Promotes an object to DRAM for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Both the key (via `Box<K, Hybrid>`) and value bytes of the source object
    /// live in PMEM.  Promotion reads the key from PMEM and copies both key and
    /// value bytes into a DRAM-resident `TieringObject<K>`.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    // Copy key (from PMEM via Box<K, Hybrid>) and value bytes
                    // (from PMEM) into a DRAM-allocated TieringObject<K>.
                    let dram_object = self.create_dram_object(object);
                    
                    // Store the TieringObject in the DRAM cache
                    self.dram_cache.insert(key, dram_object);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")),
        all(feature = "alloc_api_exp", not(feature = "hashtable_tiering"))
    ))]
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    // Create DRAM object with physical data copy
                    let dram_object = self.create_dram_object(object);
                    
                    // Store the TieringObject in the DRAM cache
                    self.dram_cache.write().unwrap().insert(key, dram_object);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }

    #[cfg(all(feature = "hashtable_tiering", feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    /// Promotes an object to warm tier (pointer-only) or hot tier (physical copy)
    /// Returns true if promotion was successful
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            let config = self.config.read().unwrap();
            
            match info.tier {
                Tier::PmemOnly => {
                    // Promote to warm tier (pointer-only, zero-copy)
                    if info.access_count >= config.warm_threshold {
                        info.tier = Tier::DramPtrToPmem;

                        // Create warm object with CXL reference
                        let warm_object = self.create_warm_object(object);
                        
                        // Store the TieringObject in the DRAM cache
                        self.dram_cache.insert(key, warm_object);

                        let mut dram_objects = self.dram_objects.write().unwrap();
                        dram_objects.insert(key);

                        let mut stats = self.stats.write().unwrap();
                        let pointer_size = self.pointer_footprint(object);
                        info.pointer_size = pointer_size;
                        stats.pointer_size = stats.pointer_size.saturating_add(pointer_size);
                        stats.dram_objects += 1;
                        stats.warm_objects = stats.warm_objects.saturating_add(1);
                        stats.pmem_only_objects -= 1;
                        stats.promotions += 1;

                        return true;
                    }
                }
                Tier::DramPtrToPmem => {
                    // Upgrade to hot tier (physical copy)
                    if info.access_count >= config.hot_threshold {
                        let mut stats = self.stats.write().unwrap();
                        let current_usage = Self::combined_usage(&stats);
                        let pointer_size = info.pointer_size;
                        let new_usage = current_usage
                            .saturating_sub(pointer_size)
                            .saturating_add(info.size as u64);

                        // Check if promotion would exceed threshold
                        if new_usage <= config.dram_threshold {
                            info.tier = Tier::DramAndPmem;

                            // Create DRAM object with physical data copy
                            let dram_object = self.create_dram_object(object);
                            
                            // Update the existing TieringObject in the DRAM cache
                            self.dram_cache.insert(key, dram_object);

                            stats.pointer_size = stats.pointer_size.saturating_sub(pointer_size);
                            stats.dram_size = stats.dram_size.saturating_add(info.size as u64);
                            stats.warm_objects = stats.warm_objects.saturating_sub(1);
                            stats.hot_objects = stats.hot_objects.saturating_add(1);
                            stats.promotions += 1;
                            info.pointer_size = 0;

                            return true;
                        }
                    }
                }
                Tier::DramAndPmem => {
                    // Already in hot tier
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Already in DRAM-only tier
                }

            }
        }

        false
    }

    #[cfg(any(
        all(feature = "hashtable_tiering", feature = "key_value_pmem", feature = "tiering_hashtable_pmem"),
        all(feature = "hashtable_tiering", feature = "alloc_api_exp")
    ))]
    /// Promotes an object to warm tier (pointer-only) or hot tier (physical copy)
    /// Returns true if promotion was successful
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            let config = self.config.read().unwrap();
            
            match info.tier {
                Tier::PmemOnly => {
                    // Promote to warm tier (pointer-only, zero-copy)
                    if info.access_count >= config.warm_threshold {
                        info.tier = Tier::DramPtrToPmem;

                        // Create warm object with CXL reference
                        let warm_object = self.create_warm_object(object);
                        
                        // Store the TieringObject in the DRAM cache
                        self.dram_cache.write().unwrap().insert(key, warm_object);

                        let mut dram_objects = self.dram_objects.write().unwrap();
                        dram_objects.insert(key);

                        let mut stats = self.stats.write().unwrap();
                        let pointer_size = self.pointer_footprint(object);
                        info.pointer_size = pointer_size;
                        stats.pointer_size = stats.pointer_size.saturating_add(pointer_size);
                        stats.dram_objects += 1;
                        stats.warm_objects = stats.warm_objects.saturating_add(1);
                        stats.pmem_only_objects -= 1;
                        stats.promotions += 1;

                        return true;
                    }
                }
                Tier::DramPtrToPmem => {
                    // Upgrade to hot tier (physical copy)
                    if info.access_count >= config.hot_threshold {
                        let mut stats = self.stats.write().unwrap();
                        let current_usage = Self::combined_usage(&stats);
                        let pointer_size = info.pointer_size;
                        let new_usage = current_usage
                            .saturating_sub(pointer_size)
                            .saturating_add(info.size as u64);

                        // Check if promotion would exceed threshold
                        if new_usage <= config.dram_threshold {
                            info.tier = Tier::DramAndPmem;

                            // Create DRAM object with physical data copy
                            let dram_object = self.create_dram_object(object);
                            
                            // Update the existing TieringObject in the DRAM cache
                            self.dram_cache.write().unwrap().insert(key, dram_object);

                            stats.pointer_size = stats.pointer_size.saturating_sub(pointer_size);
                            stats.dram_size = stats.dram_size.saturating_add(info.size as u64);
                            stats.warm_objects = stats.warm_objects.saturating_sub(1);
                            stats.hot_objects = stats.hot_objects.saturating_add(1);
                            stats.promotions += 1;
                            info.pointer_size = 0;

                            return true;
                        }
                    }
                }
                Tier::DramAndPmem => {
                    // Already in hot tier
                }
            }
        }

        false
    }
    
    /// Promotes an object to DRAM (metadata only - for tests)
    /// Returns true if promotion was successful
    /// Note: This only updates metadata, not actual data. Use promote_to_dram_with_data for production.
    #[cfg(test)]
    fn promote_to_dram(&self, key: HashedKey) -> bool {
        // This method is only for tests that don't need actual data copies
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }
    
    /// Demotes an object from DRAM (removes the DRAM copy, keeps PMEM).
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramAndPmem {
                info.tier = Tier::PmemOnly;
                //println!("Demoting object {:?} from DRAM", key);

                // Remove from DRAM cache
                self.dram_cache.remove(&key);

                let mut dram_objects = self.dram_objects.write().unwrap();
                dram_objects.remove(&key);

                let mut stats = self.stats.write().unwrap();
                stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                stats.dram_objects = stats.dram_objects.saturating_sub(1);
                stats.pmem_only_objects += 1;
                stats.demotions += 1;

                return true;
            }
        }

        false
    }

    /// Demotes an object from DRAM for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Removes the DRAM copy; the authoritative copy (both key and value in PMEM)
    /// remains untouched as the source of truth.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramAndPmem {
                info.tier = Tier::PmemOnly;

                // Remove DRAM copy; PMEM copy (both key and value in PMEM) remains
                self.dram_cache.remove(&key);

                let mut dram_objects = self.dram_objects.write().unwrap();
                dram_objects.remove(&key);

                let mut stats = self.stats.write().unwrap();
                stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                stats.dram_objects = stats.dram_objects.saturating_sub(1);
                stats.pmem_only_objects += 1;
                stats.demotions += 1;

                return true;
            }
        }

        false
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")),
        all(feature = "alloc_api_exp", not(feature = "hashtable_tiering"))
    ))]
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramAndPmem {
                info.tier = Tier::PmemOnly;
                //println!("Demoting object {:?} from DRAM", key);

                // Remove from DRAM cache
                self.dram_cache.write().unwrap().remove(&key);

                let mut dram_objects = self.dram_objects.write().unwrap();
                dram_objects.remove(&key);

                let mut stats = self.stats.write().unwrap();
                stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                stats.dram_objects = stats.dram_objects.saturating_sub(1);
                stats.pmem_only_objects += 1;
                stats.demotions += 1;

                return true;
            }
        }

        false
    }

    #[cfg(all(feature = "hashtable_tiering", feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    /// Demotes an object from DRAM (hashtable_tiering version)
    /// Handles both warm tier (pointer-only) and hot tier (physical copy)
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            match info.tier {
                Tier::DramPtrToPmem => {
                    // Demote from warm tier (pointer-only)
                    info.tier = Tier::PmemOnly;

                    // Remove from DRAM cache
                    self.dram_cache.remove(&key);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    let mut stats = self.stats.write().unwrap();
                    stats.warm_objects = stats.warm_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pmem_only_objects += 1;
                    stats.demotions += 1;
                    info.pointer_size = 0;

                    return true;
                }
                Tier::DramAndPmem => {
                    // Demote from hot tier (physical copy)
                    info.tier = Tier::PmemOnly;

                    // Remove from DRAM cache
                    self.dram_cache.remove(&key);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    let mut stats = self.stats.write().unwrap();
                    stats.hot_objects = stats.hot_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pmem_only_objects += 1;
                    stats.demotions += 1;
                    info.pointer_size = 0;

                    return true;
                }
                Tier::PmemOnly => {
                    // Already in PMEM only
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Already in DRAM-only tier, demote to PMEM only
                    info.tier = Tier::PmemOnly;
                    self.dram_cache.remove(&key);
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);
                    let mut stats = self.stats.write().unwrap();
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pmem_only_objects += 1;
                    stats.demotions += 1;

                    return true;

                    //THIS MUST ACTUALLY ENSUrE THAT THE DATA IS WRITEN TO PMEM IF WE ARE IN SETS DRAM MODE, OTHERWISE WE RISK DATA LOSS.
                }
            }
        }

        false
    }

    #[cfg(any(
        all(feature = "hashtable_tiering", feature = "key_value_pmem", feature = "tiering_hashtable_pmem"),
        all(feature = "hashtable_tiering", feature = "alloc_api_exp")
    ))]
    /// Demotes an object from DRAM (hashtable_tiering version)
    /// Handles both warm tier (pointer-only) and hot tier (physical copy)
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            match info.tier {
                Tier::DramPtrToPmem => {
                    // Demote from warm tier (pointer-only)
                    info.tier = Tier::PmemOnly;

                    // Remove from DRAM cache
                    self.dram_cache.write().unwrap().remove(&key);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    let mut stats = self.stats.write().unwrap();
                    stats.warm_objects = stats.warm_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pmem_only_objects += 1;
                    stats.demotions += 1;
                    info.pointer_size = 0;

                    return true;
                }
                Tier::DramAndPmem => {
                    // Demote from hot tier (physical copy)
                    info.tier = Tier::PmemOnly;

                    // Remove from DRAM cache
                    self.dram_cache.write().unwrap().remove(&key);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    let mut stats = self.stats.write().unwrap();
                    stats.hot_objects = stats.hot_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pmem_only_objects += 1;
                    stats.demotions += 1;
                    info.pointer_size = 0;

                    return true;
                }
                Tier::PmemOnly => {
                    // Already in PMEM only
                }
            }
        }

        false
    }
    
    /// Gets a TieringObject from the DRAM cache if it exists there.
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn get_from_dram(&self, key: &HashedKey) -> Option<impl std::ops::Deref<Target = TieringObject<K>> + '_> {
        self.dram_cache.get(key)
    }

    /// Returns the DRAM-cached `TieringObject<K>` for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// This is a physical DRAM copy produced during promotion; the authoritative
    /// copy (both key and value bytes) lives in PMEM.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn get_from_dram(&self, key: &HashedKey) -> Option<impl std::ops::Deref<Target = TieringObject<K>> + '_> {
        self.dram_cache.get(key)
    }

    #[cfg(all(feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem"), feature = "hashtable_tiering"))]
    pub fn get_from_dram(&self, key: &HashedKey) -> Option<impl std::ops::Deref<Target = TieringObject<K, V>> + '_> {
        self.dram_cache.get(key)
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")),
        all(feature = "alloc_api_exp", not(feature = "hashtable_tiering"))
    ))]
    pub fn get_from_dram(&self, key: &HashedKey) -> Option<Arc<TieringObject<K>>> {
        self.dram_cache
            .read()
            .unwrap()
            .get(key)
            .map(|obj| Arc::new(obj.clone()))
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", feature = "hashtable_tiering"),
        all(feature = "alloc_api_exp", feature = "hashtable_tiering")
    ))]
    pub fn get_from_dram(&self, key: &HashedKey) -> Option<Arc<TieringObject<K, V>>> {
        self.dram_cache
            .read()
            .unwrap()
            .get(key)
            .map(|obj| Arc::new(obj.clone()))
    }
    
    /// Updates the DRAM cache when an object is updated.
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem")))]
    pub fn update_dram_copy(&self, key: HashedKey, object: &Object<K, V>) 
    where
        V: AsRef<[u8]>,
    {
        // Only update if object is currently in DRAM
        if self.is_in_dram(&key) {
            // Create DRAM object with physical data copy
            let updated_object = self.create_dram_object(object);
            self.dram_cache.insert(key, updated_object);
        }
    }

    /// Updates the DRAM copy when a PMEM-resident object is modified, for the
    /// `tiering` feature (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Re-reads both key (from PMEM via `Box<K, Hybrid>`) and value bytes from
    /// PMEM and stores a fresh DRAM-allocated copy in the dram_cache.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    pub fn update_dram_copy(&self, key: HashedKey, object: &Object<K, V>) 
    where
        V: AsRef<[u8]>,
    {
        // Only update if object is currently in DRAM
        if self.is_in_dram(&key) {
            // Re-read key from PMEM (Box<K, Hybrid>) and copy value bytes into DRAM
            let updated_object = self.create_dram_object(object);
            self.dram_cache.insert(key, updated_object);
        }
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem"),
        feature = "alloc_api_exp"
    ))]
    pub fn update_dram_copy(&self, key: HashedKey, object: &Object<K, V>) 
    where
        V: AsRef<[u8]>,
    {
        // Only update if object is currently in DRAM
        if self.is_in_dram(&key) {
            // Create DRAM object with physical data copy
            let updated_object = self.create_dram_object(object);
            self.dram_cache.write().unwrap().insert(key, updated_object);
        }
    }

    /// Checks if DRAM threshold has been exceeded and returns keys to demote
    /// Uses LRU (Least Recently Used) strategy for demotion
    pub fn get_keys_to_demote(&self) -> Vec<HashedKey> {
        let config = self.config.read().unwrap();
        let stats = self.stats.read().unwrap();
        let mut current_usage = Self::combined_usage(&stats);
        let high_water = (config.dram_threshold as f64 * config.high_water_mark) as u64;
        let low_water = (config.dram_threshold as f64 * config.low_water_mark) as u64;

        if current_usage <= high_water {
            return Vec::new();
        }

        drop(stats);
        drop(config);

        // Find objects to demote to bring usage below low water mark
        let info_map = self.object_info.read().unwrap();
        let dram_objects = self.dram_objects.read().unwrap();

        let mut dram_object_info: Vec<(HashedKey, &ObjectTierInfo)> = dram_objects
            .iter()
            .filter_map(|key| info_map.get(key).map(|info| (*key, info)))
            .collect();

        // Sort by last access time (LRU)
        dram_object_info.sort_by_key(|(_, info)| info.last_access);

        let mut keys_to_demote = Vec::new();

        for (key, info) in dram_object_info {
            if current_usage <= low_water {
                break;
            }

            keys_to_demote.push(key);
            let mut usage = match info.tier {
                Tier::DramAndPmem => info.size as u64,
                #[cfg(feature = "hashtable_tiering")]
                Tier::DramPtrToPmem => info.pointer_size,
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => info.size as u64,
                Tier::PmemOnly => 0,
            };

            if usage == 0 {
                usage = info.size as u64;
            }

            current_usage = current_usage.saturating_sub(usage);
        }

        keys_to_demote
    }

    /// Adaptive variant of demotion that reuses the same LRU selection while
    /// honoring the adaptive feature gate so callers can compile under the
    /// `adaptive` / `adaptive_tiering` flags.
    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    pub fn get_keys_to_demote_adaptive(&self) -> Vec<HashedKey> {
        self.get_keys_to_demote()
    }

    /// Removes an object from all tiering tracking (when it's deleted from cache).
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Object is DRAM-only pending PMEM backfill. Remove from DRAM tracking.
                    // Note: if PMEM write has not yet completed, data loss may occur.
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_only_objects = stats.dram_only_objects.saturating_sub(1);
                }
            }
        }
    }

    /// Removes an object from all tiering tracking for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Cleans up the DRAM copy if present; the PMEM copy (both key and value
    /// in PMEM) is removed separately by the main cache eviction path.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem"), not(feature = "hashtable_tiering")))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove DRAM copy; PMEM copy (both key and value in PMEM)
                    // is removed by the main cache eviction path.
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Object is DRAM-only pending PMEM backfill. Remove from DRAM tracking.
                    // Note: if PMEM write has not yet completed, data loss may occur.
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_only_objects = stats.dram_only_objects.saturating_sub(1);
                }
            }
        }
    }

    #[cfg(all(feature = "key_value_pmem", not(feature = "tiering_hashtable_pmem"), feature = "hashtable_tiering"))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.hot_objects = stats.hot_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::DramPtrToPmem => {
                    // Remove from DRAM cache (pointer-only)
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.warm_objects = stats.warm_objects.saturating_sub(1);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
                
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // Remove from DRAM cache (DRAM-only tier)
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);

                    //I MUST ASERT THAT IT IS COPIED BACK TO PMEM LEVEL BEFORE REMOVING FROM DRAM-ONLY TIER, OTHERWISE DATA LOSS OCCURS.
                }
            }
        }
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", not(feature = "hashtable_tiering")),
        all(feature = "alloc_api_exp", not(feature = "hashtable_tiering"))
    ))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    self.dram_cache.write().unwrap().remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
                #[cfg(feature = "sets_dram")]
                Tier::DramOnly => {
                    // PMEM persistence must be confirmed before dropping a DramOnly object.
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_only_objects = stats.dram_only_objects.saturating_sub(1);
                }
            }
        }
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem", feature = "hashtable_tiering"),
        all(feature = "alloc_api_exp", feature = "hashtable_tiering")
    ))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    self.dram_cache.write().unwrap().remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.hot_objects = stats.hot_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::DramPtrToPmem => {
                    // Remove from DRAM cache (pointer-only)
                    self.dram_cache.write().unwrap().remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.warm_objects = stats.warm_objects.saturating_sub(1);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                    stats.pointer_size = stats.pointer_size.saturating_sub(info.pointer_size);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
            }
        }
    }

    /// Gets current tiering statistics
    pub fn stats(&self) -> TieringStats {
        self.stats.read().unwrap().clone()
    }

    /// Checks if an object is currently in DRAM
    pub fn is_in_dram(&self, key: &HashedKey) -> bool {
        self.dram_objects.read().unwrap().contains(key)
    }

    /// Updates the DRAM threshold
    pub fn set_dram_threshold(&self, threshold: u64) {
        let mut config = self.config.write().unwrap();
        config.dram_threshold = threshold;
    }

    /// Gets the current DRAM threshold
    pub fn dram_threshold(&self) -> u64 {
        self.config.read().unwrap().dram_threshold
    }

    /// Gets the current hotness threshold
    pub fn hotness_threshold(&self) -> u64 {
        self.config.read().unwrap().hotness_threshold
    }

    /// Sets the hotness threshold
    pub fn set_hotness_threshold(&self, threshold: u64) {
        let mut config = self.config.write().unwrap();
        config.hotness_threshold = threshold;
    }

    /// Clears all tiering metadata and the DRAM cache.
    /// Used when key lives in DRAM and value lives in PMEM (`key_value_pmem` only).
    #[cfg(all(feature = "key_value_pmem", not(feature = "key_pmem_value_pmem"), not(feature = "tiering_hashtable_pmem")))]
    pub fn clear(&self) {
        let mut info_map = self.object_info.write().unwrap();
        info_map.clear();

        let mut dram_objects = self.dram_objects.write().unwrap();
        dram_objects.clear();
        
        // Clear the DRAM cache
        self.dram_cache.clear();

        let mut stats = self.stats.write().unwrap();
        *stats = TieringStats::default();
    }

    /// Clears all tiering metadata and the DRAM cache for the `tiering` feature
    /// (`key_pmem_value_pmem` + `enable_tiering_manager`).
    /// Removes all DRAM copies; the PMEM copies (both key and value in PMEM)
    /// are cleared separately by the main cache wipe path.
    #[cfg(all(feature = "key_pmem_value_pmem", not(feature = "tiering_hashtable_pmem")))]
    pub fn clear(&self) {
        let mut info_map = self.object_info.write().unwrap();
        info_map.clear();

        let mut dram_objects = self.dram_objects.write().unwrap();
        dram_objects.clear();
        
        // Remove all DRAM copies; PMEM copies are cleared by the main cache wipe
        self.dram_cache.clear();

        let mut stats = self.stats.write().unwrap();
        *stats = TieringStats::default();
    }

    #[cfg(any(
        all(feature = "key_value_pmem", feature = "tiering_hashtable_pmem"),
        feature = "alloc_api_exp"
    ))]
    pub fn clear(&self) {
        let mut info_map = self.object_info.write().unwrap();
        info_map.clear();

        let mut dram_objects = self.dram_objects.write().unwrap();
        dram_objects.clear();
        
        // Clear the DRAM cache
        self.dram_cache.write().unwrap().clear();

        let mut stats = self.stats.write().unwrap();
        *stats = TieringStats::default();
    }
}

/// Methods with minimal type-parameter bounds so callers (e.g. `PolicyWorker`)
/// that don't require `Clone` on `K` can still use them.
#[cfg(feature = "sets_dram")]
impl<K, V> TieringManager<K, V> {
    /// Returns `true` if the key is currently in the `DramOnly` tier,
    /// meaning its PMEM backfill write has not yet completed.
    pub fn is_dram_only(&self, key: HashedKey) -> bool {
        self.object_info
            .read()
            .expect("object_info RwLock should not be poisoned")
            .get(&key)
            .map_or(false, |info| info.tier == Tier::DramOnly)
    }

    /// Synchronously persists a `DramOnly` key by removing its pending job
    /// from the queue and calling the persist callback inline.
    ///
    /// Returns `true` if the job was found in the pending queue and processed.
    /// Returns `false` if the job was already claimed by the background thread.
    ///
    /// This is used by the `PolicyWorker` to ensure data safety before evicting
    /// an object that hasn't yet been flushed to PMEM.
    pub fn force_sync_persist(&self, key: HashedKey) -> bool {
        if let Some(job) = self.pending_jobs
            .lock()
            .expect("pending_jobs mutex should not be poisoned")
            .remove(&key)
        {
            (self.sync_persist_fn)(vec![job]);
            true
        } else {
            false
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestManager = TieringManager<u64, Vec<u8>>;

    #[test]
    fn test_tiering_manager_creation() {
        let manager = TestManager::with_defaults();
        let stats = manager.stats();

        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
        assert_eq!(stats.promotions, 0);
        assert_eq!(stats.demotions, 0);
    }

    #[test]
    fn test_register_object() {
        let manager = TestManager::with_defaults();

        manager.register_object(1, 100);

        let stats = manager.stats();
        assert_eq!(stats.pmem_only_objects, 1);
        assert_eq!(stats.dram_objects, 0);
    }

    #[test]
    fn test_promote_to_dram() {
        let manager = TestManager::with_defaults();

        manager.register_object(1, 100);
        assert!(manager.promote_to_dram(1));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 1);
        assert_eq!(stats.dram_size, 100);
        assert_eq!(stats.promotions, 1);
        assert!(manager.is_in_dram(&1));
    }

    #[test]
    fn test_demote_from_dram() {
        let manager = TestManager::with_defaults();

        manager.register_object(1, 100);
        manager.promote_to_dram(1);
        assert!(manager.demote_from_dram(1));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
        assert_eq!(stats.demotions, 1);
        assert!(!manager.is_in_dram(&1));
    }

    #[test]
    fn test_threshold_enforcement() {
        let config = TieringConfig {
            dram_threshold: 200,
            high_water_mark: 0.9,
            low_water_mark: 0.7,
            hotness_threshold: 1,
            ..TieringConfig::default()
        };
        let manager = TestManager::new(config);

        // Promote two objects, total 200 bytes (at threshold)
        manager.register_object(1, 100);
        manager.register_object(2, 100);

        assert!(manager.promote_to_dram(1));
        assert!(manager.promote_to_dram(2));

        // Try to promote a third object (would exceed threshold)
        manager.register_object(3, 100);
        assert!(!manager.promote_to_dram(3));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 2);
    }

    #[test]
    fn test_remove_object() {
        let manager = TestManager::with_defaults();

        manager.register_object(1, 100);
        manager.promote_to_dram(1);
        manager.remove_object(1);

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
    }

    #[test]
    fn test_access_recording() {
        let manager = TestManager::with_defaults();

        // Lower the threshold to 2 accesses for this test scenario.
        manager.set_hotness_threshold(2);

        manager.register_object(1, 100);

        // First access - should not promote yet (threshold is 2)
        assert!(!manager.record_access(1));

        // Second access - should suggest promotion
        assert!(manager.record_access(1));
    }

    #[cfg(any(feature = "adaptive_tiering", feature = "adaptive"))]
    #[test]
    fn adaptive_requires_second_touch_before_promotion() {
        let manager = TestManager::with_defaults();
        manager.register_object(1, 512);

        // First access only seeds recency/size tracking.
        assert!(!manager.record_access_adaptive(1));

        // Second access is eligible for promotion under adaptive rules.
        assert!(manager.record_access_adaptive(1));
    }

    #[test]
    fn test_configurable_hotness_threshold() {
        let mut config = TieringConfig::default();
        config.hotness_threshold = 3;
        let manager = TestManager::new(config);

        manager.register_object(1, 100);

        // First two accesses should not promote
        assert!(!manager.record_access(1));
        assert!(!manager.record_access(1));

        // Third access should suggest promotion
        assert!(manager.record_access(1));
    }

    #[test]
    fn test_get_keys_to_demote() {
        let config = TieringConfig {
            dram_threshold: 300,
            high_water_mark: 0.9,
            low_water_mark: 0.6,
            hotness_threshold: 1,
            ..TieringConfig::default()
        };
        let manager = TestManager::new(config);

        // Register and promote 4 objects
        for i in 1..=4 {
            manager.register_object(i, 100);
            manager.promote_to_dram(i);
            std::thread::sleep(std::time::Duration::from_millis(10));
        }

        // DRAM size is now 400, threshold is 300
        // High water mark: 270, Low water mark: 180
        // Should demote to bring below 180
        let keys_to_demote = manager.get_keys_to_demote();
        
        // Should demote at least 2 objects (200 bytes)
        assert!(keys_to_demote.len() >= 2);
    }

    #[test]
    fn test_set_and_get_hotness_threshold() {
        let manager = TestManager::with_defaults();
        
        assert_eq!(manager.hotness_threshold(), 3);
        
        manager.set_hotness_threshold(5);
        assert_eq!(manager.hotness_threshold(), 5);
    }
}
