use std::{
    collections::{HashMap, HashSet},
    sync::{Arc, RwLock},
};




use dashmap::DashMap;
use typesize::TypeSize;

use crate::{
    HashedKey,
    object::{Object, ObjectSize},
    //NoHasher,
};

use nohash_hasher::NoHashHasher;

use std::hash::BuildHasherDefault;

pub type NoHasher = BuildHasherDefault<NoHashHasher<HashedKey>>;

#[cfg(any(feature = "allocator_api", feature = "alloc_with_hash", feature = "alloc_api_exp"))]
use crate::allocator::HybridObjects as Hybrid;


mod allocator_bindings {
    include!("../umf_allocator_bindings.rs"); // generated by bindgen
}

#[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
use hashbrown::HashMap as hashtable;


/// Configuration for the tiering manager
#[derive(Debug, Clone)]
pub struct TieringConfig {
    /// Threshold for DRAM usage in bytes
    /// When DRAM usage exceeds this threshold, cold objects are demoted from DRAM to PMEM
    pub dram_threshold: u64,

    /// High water mark as percentage of threshold (0.0 to 1.0)
    /// When DRAM usage exceeds threshold * high_water_mark, start demoting
    pub high_water_mark: f64,

    /// Low water mark as percentage of threshold (0.0 to 1.0)
    /// Continue demoting until DRAM usage falls below threshold * low_water_mark
    pub low_water_mark: f64,

    /// Hotness threshold: minimum access count before promotion
    pub hotness_threshold: u64,
}

impl Default for TieringConfig {
    fn default() -> Self {
        TieringConfig {
            dram_threshold: 1 * 1024 * 1024 * 1024 + 512 * 1024 * 1024, // 1.5 GB default
            high_water_mark: 0.98,
            low_water_mark: 0.7,
            hotness_threshold: 3, // Promote after 3 accesses
        }
    }
}

/// Statistics for the tiering manager
#[derive(Debug, Clone, Default)]
pub struct TieringStats {
    /// Number of objects currently in DRAM
    pub dram_objects: u64,

    /// Total size of objects in DRAM (bytes)
    pub dram_size: u64,

    /// Number of promotions from PMEM to DRAM
    pub promotions: u64,

    /// Number of demotions from DRAM to PMEM
    pub demotions: u64,

    /// Number of objects only in PMEM
    pub pmem_only_objects: u64,
}

/// Tier location for an object
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Tier {
    /// Object exists in both DRAM (copy) and PMEM (source of truth)
    DramAndPmem,

    /// Object exists only in PMEM
    PmemOnly,
}

/// Information about an object's tiering status
#[derive(Debug, Clone)]
struct ObjectTierInfo {
    /// Current tier location
    tier: Tier,

    /// Size of the object in bytes
    size: ObjectSize,

    /// Access count (for LFU-like promotion/demotion)
    access_count: u64,

    /// Last access timestamp (for LRU-like promotion/demotion)
    last_access: std::time::Instant,
}

/// Tiering Manager
/// 
/// Manages object placement between DRAM and PMEM tiers.
/// DRAM contains hot COPIES of objects while PMEM is the source of truth.
/// 
/// ## Data Copy Model
/// Hot objects are physically copied to a DRAM cache for fast access.
/// The PMEM tier always contains all objects (source of truth).
/// DRAM tier contains copies of frequently accessed objects.
/// 
/// ## Promotion Policy
/// Objects are promoted to DRAM after being accessed more than the configured threshold.
/// This simple heuristic ensures that only objects with repeated access are promoted.
pub struct TieringManager<K, V> {
    config: Arc<RwLock<TieringConfig>>,
    stats: Arc<RwLock<TieringStats>>,

    /// Tracking information for each object
    object_info: Arc<RwLock<HashMap<HashedKey, ObjectTierInfo>>>,

    /// Set of objects currently in DRAM (for fast lookup)
    dram_objects: Arc<RwLock<HashSet<HashedKey>>>,
    
    /// DRAM cache storing Object<K, Box<[u8]>> instances with physically allocated DRAM data
    
    /// Uses the same Object structure as main cache but with DRAM-allocated Box<[u8]> instead of V
    
    #[cfg(feature = "allocator_api")]
    dram_cache: Arc<DashMap<HashedKey, Object<K, Box<[u8]>>, NoHasher>>,
    
    #[cfg(feature = "alloc_with_hash")]
    dram_cache: Arc<RwLock<hashtable<HashedKey, Object<K, Box<[u8]>>, BuildHasherDefault<NoHashHasher<u64>>, Hybrid>>>,

    #[cfg(feature = "alloc_api_exp")]
    dram_cache: Arc<RwLock<hashtable<HashedKey, Object<K, Box<[u8]>>, BuildHasherDefault<NoHashHasher<u64>>>>>,

    _phantom: std::marker::PhantomData<(K, V)>,
}

impl<K, V> TieringManager<K, V>
where
    K: TypeSize + Clone,
    V: TypeSize + Clone,
{
    /// Creates a new TieringManager with the given configuration
    
    #[cfg(feature = "allocator_api")]
    pub fn new(config: TieringConfig) -> Self {
        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())), //this is probs redundant and not needed.... 
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(DashMap::with_hasher(NoHasher::default())),
            _phantom: std::marker::PhantomData,
        }
    }

   #[cfg(feature = "alloc_api_exp")]
    pub fn new(config: TieringConfig) -> Self {
        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())), //this is probs redundant and not needed.... 
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher(NoHasher::default()))),
            _phantom: std::marker::PhantomData,
        }
    }


   #[cfg(feature = "alloc_with_hash")]
    pub fn new(config: TieringConfig) -> Self {
        TieringManager {
            config: Arc::new(RwLock::new(config)),
            stats: Arc::new(RwLock::new(TieringStats::default())),
            object_info: Arc::new(RwLock::new(HashMap::new())), //this is probs redundant and not needed.... 
            dram_objects: Arc::new(RwLock::new(HashSet::new())),
            dram_cache: Arc::new(RwLock::new(hashtable::with_hasher_in(NoHasher::default(), Hybrid))),
            _phantom: std::marker::PhantomData,
        }
    }



    /// Creates a new TieringManager with default configuration
    pub fn with_defaults() -> Self {
        Self::new(TieringConfig::default())
    }

    /// Registers a new object in PMEM
    pub fn register_object(&self, key: HashedKey, size: ObjectSize) {
        let mut info_map = self.object_info.write().unwrap();

        info_map.insert(key, ObjectTierInfo {
            tier: Tier::PmemOnly,
            size,
            access_count: 0,
            last_access: std::time::Instant::now(),
        });

        let mut stats = self.stats.write().unwrap();
        stats.pmem_only_objects += 1;
    }

    /// Records an access to an object
    /// Returns true if the object should be promoted to DRAM
    /// 
    /// ## Promotion Heuristic
    /// Objects are promoted after reaching the configured hotness threshold.
    pub fn record_access(&self, key: HashedKey) -> bool {
        let config = self.config.read().unwrap();
        let hotness_threshold = config.hotness_threshold;
        drop(config);

        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            info.access_count += 1;
            info.last_access = std::time::Instant::now();

            // Decide if promotion is needed

            //umf_allocator_bindings::check_tier();

            match info.tier {
                Tier::PmemOnly => {
                    // Check if we should promote based on access count
                    info.access_count >= hotness_threshold
                }
                Tier::DramAndPmem => {
                    // Already in DRAM
                    false
                }
            }
        } else {
            false
        }
    }

    /// Helper method to create a DRAM Object with physically copied data
    /// Extracts bytes from source object and creates a new DRAM-allocated copy
    fn create_dram_object(&self, object: &Object<K, V>) -> Object<K, Box<[u8]>>
    where
        V: AsRef<[u8]>,
    {
        // Extract bytes from source (which may be PMEM-allocated)
        let source_data = object.data();
        // First .as_ref() dereferences Arc<V> -> &V
        // Second .as_ref() calls AsRef<[u8]> trait on V -> &[u8]
        let bytes: &[u8] = source_data.as_ref().as_ref();
        
        // Create new DRAM-allocated Box<[u8]> (physical copy)
        let dram_data: Box<[u8]> = bytes.to_vec().into_boxed_slice();
        
        // Create new Object with cloned key, DRAM-allocated data, and same expiry
        Object::with_expiry(object.key().clone(), dram_data, object.expiry())
    }

    /// Promotes an object to DRAM by creating a physical copy with DRAM-allocated data
    /// Returns true if promotion was successful
    /// The object parameter is the Object from the main cache to copy to DRAM
    #[cfg(feature = "allocator_api")]
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    // Create DRAM object with physical data copy
                    let dram_object = self.create_dram_object(object);
                    
                    // Store the Object in the DRAM cache
                    self.dram_cache.insert(key, dram_object);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }





    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    pub fn promote_to_dram_with_object(&self, key: HashedKey, object: &Object<K, V>) -> bool 
    where
        V: AsRef<[u8]>,
    {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    // Create DRAM object with physical data copy
                    let dram_object = self.create_dram_object(object);
                    
                    // Store the Object in the DRAM cache
                    //self.dram_cache.insert(key, dram_object);
                    self.dram_cache.write().unwrap().insert(key, dram_object);

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }
    
    /// Promotes an object to DRAM (metadata only - for tests)
    /// Returns true if promotion was successful
    /// Note: This only updates metadata, not actual data. Use promote_to_dram_with_data for production.
    #[cfg(all(test, feature = "allocator_api"))]
    fn promote_to_dram(&self, key: HashedKey) -> bool {
        // This method is only for tests that don't need actual data copies
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }







   #[cfg(all(test, feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    fn promote_to_dram(&self, key: HashedKey) -> bool {
        // This method is only for tests that don't need actual data copies
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::PmemOnly {
                let config = self.config.read().unwrap();
                let mut stats = self.stats.write().unwrap();
                let new_dram_size = stats.dram_size + info.size as u64;

                // Check if promotion would exceed threshold
                if new_dram_size <= config.dram_threshold {
                    info.tier = Tier::DramAndPmem;

                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.insert(key);

                    stats.dram_size = new_dram_size;
                    stats.dram_objects += 1;
                    stats.pmem_only_objects -= 1;
                    stats.promotions += 1;

                    return true;
                }
            }
        }

        false
    }

    /// Demotes an object from DRAM (removes the DRAM copy, keeps PMEM)
    /// Returns true if demotion was successful
    #[cfg(feature = "allocator_api")]
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramAndPmem {
                info.tier = Tier::PmemOnly;
                //println!("Demoting object {:?} from DRAM", key);

                // Remove from DRAM cache
                self.dram_cache.remove(&key);

                let mut dram_objects = self.dram_objects.write().unwrap();
                dram_objects.remove(&key);

                let mut stats = self.stats.write().unwrap();
                stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                stats.dram_objects = stats.dram_objects.saturating_sub(1);
                stats.pmem_only_objects += 1;
                stats.demotions += 1;

                return true;
            }
        }

        false
    }



    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    pub fn demote_from_dram(&self, key: HashedKey) -> bool {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.get_mut(&key) {
            if info.tier == Tier::DramAndPmem {
                info.tier = Tier::PmemOnly;
                //println!("Demoting object {:?} from DRAM", key);

                // Remove from DRAM cache
                //self.dram_cache.remove(&key);
                self.dram_cache.write().unwrap().remove(&key);

                let mut dram_objects = self.dram_objects.write().unwrap();
                dram_objects.remove(&key);

                let mut stats = self.stats.write().unwrap();
                stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                stats.dram_objects = stats.dram_objects.saturating_sub(1);
                stats.pmem_only_objects += 1;
                stats.demotions += 1;

                return true;
            }
        }

        false
    }
    
    /// Gets data from the DRAM cache if it exists and matches the given key
    /// Returns owned Vec<u8> to avoid dangling references during tiering operations
    /// 
    /// SAFETY: This method copies the data immediately while holding the read lock,
    /// preventing use-after-free if the object is concurrently demoted from DRAM.
    /// 
    /// The data is copied atomically within the lock scope, ensuring that:
    /// 1. Object cannot be demoted while we're reading it
    /// 2. Returned data is fully owned and stable (no references to movable memory)
    /// 3. No use-after-free even if object is immediately demoted after this call
    /// 
    /// Returns None if:
    /// - Key not found in DRAM cache
    /// - Object is expired
    /// - Key doesn't match (hash collision)
    /// 
    /// Implementation notes:
    /// - allocator_api: DashMap::get() returns a Ref guard that holds a read lock
    /// - alloc_with_hash/alloc_api_exp: Explicit RwLock::read() for thread safety
    /// - Both approaches ensure data is copied before the lock is released
    #[cfg(feature = "allocator_api")]
    pub fn get_data_from_dram(&self, key: &K, hashed_key: &HashedKey) -> Option<Vec<u8>> 
    where
        K: Eq + std::fmt::Debug,
    {
        // DashMap::get() returns a Ref guard that holds a read lock on this entry
        // The lock is held until the Ref is dropped (at the end of and_then)
        self.dram_cache.get(hashed_key).and_then(|obj| {
            // Verify key matches (handle hash collisions)
            if !obj.key_matches(key) {
                return None;
            }
            // Check if expired - don't return expired data
            if obj.is_expired() {
                return None;
            }
            // Copy data immediately while holding reference
            // This is safe because we copy the bytes, not keep a reference
            Some(obj.data().as_ref().to_vec())
        })
    }

    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    pub fn get_data_from_dram(&self, key: &K, hashed_key: &HashedKey) -> Option<Vec<u8>> 
    where
        K: Eq + std::fmt::Debug,
    {
        // Explicit read lock for hashtable wrapped in RwLock
        self.dram_cache
            .read()
            .unwrap()
            .get(hashed_key)
            .and_then(|obj| {
                // Verify key matches (handle hash collisions)
                if !obj.key_matches(key) {
                    return None;
                }
                // Check if expired - don't return expired data
                if obj.is_expired() {
                    return None;
                }
                // Copy data immediately while holding read lock
                // This prevents use-after-free if object is demoted concurrently
                // We copy the actual bytes, not keep any references to the Object
                Some(obj.data().as_ref().to_vec())
            })
    }

    //pub fn get_from_dram(&self, key: &HashedKey) -> Option<impl std::ops::Deref<Target = Object<K, Box<[u8]>>> + '_> {
    //    let dram_cache = self.dram_cache.read().unwrap();
    //    dram_cache.get(key)
    //}

    
    /// Updates the DRAM cache when an object is updated
    /// Should be called whenever an object in PMEM is updated
    /// This creates a new physical copy with DRAM-allocated data
    #[cfg(feature = "allocator_api")]
    pub fn update_dram_copy(&self, key: HashedKey, object: &Object<K, V>) 
    where
        V: AsRef<[u8]>,
    {
        // Only update if object is currently in DRAM
        if self.is_in_dram(&key) {
            // Create DRAM object with physical data copy
            let updated_object = self.create_dram_object(object);
            self.dram_cache.insert(key, updated_object);
        }
    }


    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    pub fn update_dram_copy(&self, key: HashedKey, object: &Object<K, V>) 
    where
        V: AsRef<[u8]>,
    {
        // Only update if object is currently in DRAM
        if self.is_in_dram(&key) {
            // Create DRAM object with physical data copy
            let updated_object = self.create_dram_object(object);
            //self.dram_cache.insert(key, updated_object);
            self.dram_cache.write().unwrap().insert(key, updated_object);
        }
    }

    /// Checks if DRAM threshold has been exceeded and returns keys to demote
    /// Uses LRU (Least Recently Used) strategy for demotion
    pub fn get_keys_to_demote(&self) -> Vec<HashedKey> {
        let config = self.config.read().unwrap();
        let stats = self.stats.read().unwrap();
        let high_water = (config.dram_threshold as f64 * config.high_water_mark) as u64;

        if stats.dram_size <= high_water {
            return Vec::new();
        }

        drop(stats);
        drop(config);

        // Find objects to demote to bring usage below low water mark
        let info_map = self.object_info.read().unwrap();
        let dram_objects = self.dram_objects.read().unwrap();

        let mut dram_object_info: Vec<(HashedKey, &ObjectTierInfo)> = dram_objects
            .iter()
            .filter_map(|key| info_map.get(key).map(|info| (*key, info)))
            .collect();

        // Sort by last access time (LRU)
        dram_object_info.sort_by_key(|(_, info)| info.last_access);

        let config = self.config.read().unwrap();
        let stats = self.stats.read().unwrap();
        let mut current_size = stats.dram_size;
        let mut keys_to_demote = Vec::new();
        let low_water = (config.dram_threshold as f64 * config.low_water_mark) as u64;

        for (key, info) in dram_object_info {
            if current_size <= low_water {
                break;
            }

            keys_to_demote.push(key);
            current_size = current_size.saturating_sub(info.size as u64);
        }

        keys_to_demote
    }

    /// Removes an object from tracking (when it's deleted from cache)
    #[cfg(feature = "allocator_api")]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    self.dram_cache.remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
            }
        }
    }

    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
    pub fn remove_object(&self, key: HashedKey) {
        let mut info_map = self.object_info.write().unwrap();

        if let Some(info) = info_map.remove(&key) {
            let mut stats = self.stats.write().unwrap();

            match info.tier {
                Tier::DramAndPmem => {
                    // Remove from DRAM cache
                    //self.dram_cache.remove(&key);
                    self.dram_cache.write().unwrap().remove(&key);
                    
                    let mut dram_objects = self.dram_objects.write().unwrap();
                    dram_objects.remove(&key);

                    stats.dram_size = stats.dram_size.saturating_sub(info.size as u64);
                    stats.dram_objects = stats.dram_objects.saturating_sub(1);
                }
                Tier::PmemOnly => {
                    stats.pmem_only_objects = stats.pmem_only_objects.saturating_sub(1);
                }
            }
        }
    }

    /// Gets current tiering statistics
    pub fn stats(&self) -> TieringStats {
        self.stats.read().unwrap().clone()
    }

    /// Checks if an object is currently in DRAM
    pub fn is_in_dram(&self, key: &HashedKey) -> bool {
        self.dram_objects.read().unwrap().contains(key)
    }

    /// Updates the DRAM threshold
    pub fn set_dram_threshold(&self, threshold: u64) {
        let mut config = self.config.write().unwrap();
        config.dram_threshold = threshold;
    }

    /// Gets the current DRAM threshold
    pub fn dram_threshold(&self) -> u64 {
        self.config.read().unwrap().dram_threshold
    }

    /// Gets the current hotness threshold
    pub fn hotness_threshold(&self) -> u64 {
        self.config.read().unwrap().hotness_threshold
    }

    /// Sets the hotness threshold
    pub fn set_hotness_threshold(&self, threshold: u64) {
        let mut config = self.config.write().unwrap();
        config.hotness_threshold = threshold;
    }

    /// Clears all tiering information (for cache wipe)
    #[cfg(feature = "allocator_api")]
    pub fn clear(&self) {
        let mut info_map = self.object_info.write().unwrap();
        info_map.clear();

        let mut dram_objects = self.dram_objects.write().unwrap();
        dram_objects.clear();
        
        // Clear the DRAM cache
        self.dram_cache.clear();

        let mut stats = self.stats.write().unwrap();
        *stats = TieringStats::default();
    }

    #[cfg(any(feature = "alloc_with_hash", feature = "alloc_api_exp"))]
        pub fn clear(&self) {
        let mut info_map = self.object_info.write().unwrap();
        info_map.clear();

        let mut dram_objects = self.dram_objects.write().unwrap();
        dram_objects.clear();
        
        // Clear the DRAM cache
        self.dram_cache.write().unwrap().clear();

        let mut stats = self.stats.write().unwrap();
        *stats = TieringStats::default();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tiering_manager_creation() {
        let manager = TieringManager::with_defaults();
        let stats = manager.stats();

        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
        assert_eq!(stats.promotions, 0);
        assert_eq!(stats.demotions, 0);
    }

    #[test]
    fn test_register_object() {
        let manager = TieringManager::with_defaults();

        manager.register_object(1, 100);

        let stats = manager.stats();
        assert_eq!(stats.pmem_only_objects, 1);
        assert_eq!(stats.dram_objects, 0);
    }

    #[test]
    fn test_promote_to_dram() {
        let manager = TieringManager::with_defaults();

        manager.register_object(1, 100);
        assert!(manager.promote_to_dram(1));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 1);
        assert_eq!(stats.dram_size, 100);
        assert_eq!(stats.promotions, 1);
        assert!(manager.is_in_dram(&1));
    }

    #[test]
    fn test_demote_from_dram() {
        let manager = TieringManager::with_defaults();

        manager.register_object(1, 100);
        manager.promote_to_dram(1);
        assert!(manager.demote_from_dram(1));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
        assert_eq!(stats.demotions, 1);
        assert!(!manager.is_in_dram(&1));
    }

    #[test]
    fn test_threshold_enforcement() {
        let config = TieringConfig {
            dram_threshold: 200,
            high_water_mark: 0.9,
            low_water_mark: 0.7,
            hotness_threshold: 1,
        };
        let manager = TieringManager::new(config);

        // Promote two objects, total 200 bytes (at threshold)
        manager.register_object(1, 100);
        manager.register_object(2, 100);

        assert!(manager.promote_to_dram(1));
        assert!(manager.promote_to_dram(2));

        // Try to promote a third object (would exceed threshold)
        manager.register_object(3, 100);
        assert!(!manager.promote_to_dram(3));

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 2);
    }

    #[test]
    fn test_remove_object() {
        let manager = TieringManager::with_defaults();

        manager.register_object(1, 100);
        manager.promote_to_dram(1);
        manager.remove_object(1);

        let stats = manager.stats();
        assert_eq!(stats.dram_objects, 0);
        assert_eq!(stats.dram_size, 0);
    }

    #[test]
    fn test_access_recording() {
        let manager = TieringManager::with_defaults();

        manager.register_object(1, 100);

        // First access - should not promote yet (threshold is 2)
        assert!(!manager.record_access(1));

        // Second access - should suggest promotion
        assert!(manager.record_access(1));
    }

    #[test]
    fn test_configurable_hotness_threshold() {
        let mut config = TieringConfig::default();
        config.hotness_threshold = 3;
        let manager = TieringManager::new(config);

        manager.register_object(1, 100);

        // First two accesses should not promote
        assert!(!manager.record_access(1));
        assert!(!manager.record_access(1));

        // Third access should suggest promotion
        assert!(manager.record_access(1));
    }

    #[test]
    fn test_get_keys_to_demote() {
        let config = TieringConfig {
            dram_threshold: 300,
            high_water_mark: 0.9,
            low_water_mark: 0.6,
            hotness_threshold: 1,
        };
        let manager = TieringManager::new(config);

        // Register and promote 4 objects
        for i in 1..=4 {
            manager.register_object(i, 100);
            manager.promote_to_dram(i);
            std::thread::sleep(std::time::Duration::from_millis(10));
        }

        // DRAM size is now 400, threshold is 300
        // High water mark: 270, Low water mark: 180
        // Should demote to bring below 180
        let keys_to_demote = manager.get_keys_to_demote();
        
        // Should demote at least 2 objects (200 bytes)
        assert!(keys_to_demote.len() >= 2);
    }

    #[test]
    fn test_set_and_get_hotness_threshold() {
        let manager = TieringManager::with_defaults();
        
        assert_eq!(manager.hotness_threshold(), 2);
        
        manager.set_hotness_threshold(5);
        assert_eq!(manager.hotness_threshold(), 5);
    }
}

