

// Hybrid allocator using DRAM (jemalloc) up to a limit, then PMEM (UMF)
use core::alloc::{GlobalAlloc, Layout};
use tikv_jemallocator::Jemalloc;
use std::alloc::{Allocator, AllocError};
use std::ptr::NonNull;

// UMF bindings are only needed when we actually call into PMEM hardware.
// When `all_dram` is enabled every HybridObjects allocation is satisfied by
// jemalloc, so the UMF symbols must not be referenced (they would cause
// linker errors on machines without the UMF shared library).
#[cfg(not(feature = "all_dram"))]
mod allocator_bindings {
    include!("umf_allocator_bindings.rs"); // generated by bindgen
}

/// Hybrid allocator: first DRAM up to a limit, then PMEM
///
/// When the `all_dram` feature is active every allocation is satisfied by
/// jemalloc — no UMF functions are called, so the allocator is usable in
/// environments without PMEM hardware (e.g. CI, developer machines).
#[derive(Clone, Copy)]
pub struct HybridObjects;

// ── all_dram path ─────────────────────────────────────────────────────────────
//
// When `all_dram` is enabled the Hybrid allocator degenerates to plain
// jemalloc.  No UMF symbols are referenced, so this compiles and links on
// any machine regardless of whether UMF/PMEM hardware is present.

#[cfg(feature = "all_dram")]
unsafe impl GlobalAlloc for HybridObjects {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        Jemalloc.alloc(layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        Jemalloc.dealloc(ptr, layout);
    }
}

#[cfg(feature = "all_dram")]
unsafe impl Allocator for HybridObjects {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        unsafe {
            Jemalloc.alloc(layout)
                .as_mut()
                .map(|ptr| NonNull::slice_from_raw_parts(
                    NonNull::new_unchecked(ptr),
                    layout.size(),
                ))
                .ok_or(AllocError)
        }
    }
    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        unsafe { Jemalloc.dealloc(ptr.as_ptr(), layout); }
    }
}

#[cfg(all(feature = "all_dram", any(feature = "global_hashtable_pmem", feature = "tiering_hashtable_pmem", feature = "eviction_stacks_pmem")))]
unsafe impl allocator_api2::alloc::Allocator for HybridObjects {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, allocator_api2::alloc::AllocError> {
        let ptr = unsafe { Jemalloc.alloc(layout) };
        if ptr.is_null() {
            Err(allocator_api2::alloc::AllocError)
        } else {
            let slice = unsafe { std::slice::from_raw_parts_mut(ptr, layout.size()) };
            Ok(NonNull::from(slice))
        }
    }
    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        unsafe { Jemalloc.dealloc(ptr.as_ptr(), layout) }
    }
}

// ── PMEM / hybrid path ────────────────────────────────────────────────────────
//
// When `all_dram` is NOT enabled the allocator uses UMF (Unified Memory
// Framework) to allocate in persistent/CXL memory.  These paths require the
// UMF shared library to be present at link time.

#[cfg(not(feature = "all_dram"))]
use std::sync::{Once, atomic::{AtomicUsize, Ordering}};
#[cfg(not(feature = "all_dram"))]
use std::ptr;

// Constants for DRAM limit configuration
#[cfg(not(feature = "all_dram"))]
const ALL_DRAM_LIMIT_BYTES: usize = 1000 * 1024 * 1024 * 1024; // 1 TB
#[cfg(not(feature = "all_dram"))]
const ALL_PMEM_LIMIT_BYTES: usize = 0; // 0 bytes - everything goes to PMEM

#[cfg(not(feature = "all_dram"))]
static INIT: Once = Once::new();
#[cfg(not(feature = "all_dram"))]
static DRAM_ALLOCATED_OBJECTS: AtomicUsize = AtomicUsize::new(0);

#[cfg(not(feature = "all_dram"))]
static mut DRAM_LIMIT_OBJECTS: usize = ALL_PMEM_LIMIT_BYTES; // All in PMEM by default

// ── PMEM / hybrid GlobalAlloc (only when all_dram is NOT set) ─────────────────

#[cfg(not(feature = "all_dram"))]
static PRINT_THRESHOLD: usize = 10000;
#[cfg(not(feature = "all_dram"))]
static mut NUM_ALLOCS: usize = 0;
#[cfg(not(feature = "all_dram"))]
static mut NUM_DEALLOCS: usize = 0;
#[cfg(not(feature = "all_dram"))]
static ALL_MEM_ALLOCATED: AtomicUsize = AtomicUsize::new(0);

#[cfg(not(feature = "all_dram"))]
unsafe impl GlobalAlloc for HybridObjects {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        if DRAM_LIMIT_OBJECTS == ALL_PMEM_LIMIT_BYTES {
            unsafe {
                #[cfg(debug_assertions)] {println!("Initializing PMEM allocator with NUMA");}
                INIT.call_once(|| {
                    let numa_node = 1;
                    let numa_list = [0, 1];
                    allocator_bindings::umf_allocator_init(numa_node);
                    #[cfg(debug_assertions)] {println!("Initialized PMEM allocator with NUMA list {:?}", numa_list);}
                });
            }
            let ptr = allocator_bindings::umf_alloc(layout.size(), layout.align()) as *mut u8;
            if ptr.is_null() { println!("Failed to allocate PMEM in cache allocator"); return ptr::null_mut(); }
            #[cfg(debug_assertions)] {println!("CACHE: Allocated {} bytes from PMEM", layout.size());}
            return ptr;
        }

        let raw = if Self::should_use_dram(layout.size()) {
            let ptr = Jemalloc.alloc(layout);
            if ptr.is_null() { println!("Failed to allocate DRAM"); return ptr::null_mut(); }
            DRAM_ALLOCATED_OBJECTS.fetch_add(layout.size(), Ordering::SeqCst);
            #[cfg(debug_assertions)] {ALL_MEM_ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);}
            ptr
        } else {
            unsafe {
                INIT.call_once(|| {
                    let numa_node = 1;
                    let numa_list = [0, 1];
                    #[cfg(debug_assertions)] {println!("Initializing PMEM allocator with NUMA");}
                    allocator_bindings::umf_allocator_init(numa_node);
                    #[cfg(debug_assertions)] {println!("Initialized PMEM allocator with NUMA list {:?}", numa_list);}
                });
            }
            let ptr = allocator_bindings::umf_alloc(layout.size(), layout.align()) as *mut u8;
            if ptr.is_null() { println!("Failed to allocate PMEM"); return ptr::null_mut(); }
            #[cfg(debug_assertions)] {ALL_MEM_ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);}
            ptr
        };

        #[cfg(debug_assertions)] {
            unsafe {
                if PRINT_THRESHOLD < NUM_ALLOCS {
                    let total_alloc = ALL_MEM_ALLOCATED.load(Ordering::SeqCst);
                    let dram_alloc = DRAM_ALLOCATED_OBJECTS.load(Ordering::SeqCst);
                    println!("Allocated: total {} bytes, DRAM {} bytes ({:.2}%), PMEM {} bytes ({:.2}%)",
                        total_alloc,
                        dram_alloc,
                        dram_alloc as f64 / total_alloc as f64 * 100.0,
                        total_alloc - dram_alloc,
                        (total_alloc - dram_alloc) as f64 / total_alloc as f64 * 100.0,
                    );
                    NUM_ALLOCS = 0;
                }
                NUM_ALLOCS += 1;
            }
        }
        raw
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        if DRAM_LIMIT_OBJECTS == ALL_PMEM_LIMIT_BYTES {
            unsafe { allocator_bindings::umf_dealloc(ptr as *mut std::ffi::c_void); }
            #[cfg(debug_assertions)] { ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst); }
            return;
        }

        let tier = unsafe { allocator_bindings::check_tier(ptr as *mut std::ffi::c_void) };

        if tier == 0 {
            unsafe { Jemalloc.dealloc(ptr as *mut u8, layout); }
            DRAM_ALLOCATED_OBJECTS.fetch_sub(layout.size(), Ordering::SeqCst);
            #[cfg(debug_assertions)] { ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst); }
        } else {
            unsafe { allocator_bindings::umf_dealloc(ptr as *mut std::ffi::c_void); }
            #[cfg(debug_assertions)] { ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst); }
        }

        #[cfg(debug_assertions)] {
            unsafe {
                if PRINT_THRESHOLD < NUM_DEALLOCS {
                    let total_alloc = ALL_MEM_ALLOCATED.load(Ordering::SeqCst);
                    let dram_alloc = DRAM_ALLOCATED_OBJECTS.load(Ordering::SeqCst);
                    println!("Allocated: total {} bytes, DRAM {} bytes ({:.2}%), PMEM {} bytes ({:.2}%)",
                        total_alloc,
                        dram_alloc,
                        dram_alloc as f64 / total_alloc as f64 * 100.0,
                        total_alloc - dram_alloc,
                        (total_alloc - dram_alloc) as f64 / total_alloc as f64 * 100.0,
                    );
                    NUM_DEALLOCS = 0;
                }
                NUM_DEALLOCS += 1;
            }
        }
    }
}

#[cfg(not(feature = "all_dram"))]
impl HybridObjects {
    /// Determine whether to allocate from DRAM
    fn should_use_dram(size: usize) -> bool {
        let current = DRAM_ALLOCATED_OBJECTS.load(Ordering::SeqCst);
        unsafe { current + size <= DRAM_LIMIT_OBJECTS }
    }
}

// Allocator + allocator_api2 impls for the PMEM path (delegates to GlobalAlloc)
#[cfg(not(feature = "all_dram"))]
unsafe impl Allocator for HybridObjects {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        unsafe {
            HybridObjects::alloc(self, layout)
                .as_mut()
                .map(|ptr| NonNull::slice_from_raw_parts(NonNull::new_unchecked(ptr), layout.size()))
                .ok_or(AllocError)
        }
    }
    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        HybridObjects::dealloc(self, ptr.as_ptr(), layout);
    }
}

#[cfg(all(not(feature = "all_dram"), any(feature = "global_hashtable_pmem", feature = "tiering_hashtable_pmem", feature = "eviction_stacks_pmem")))]
unsafe impl allocator_api2::alloc::Allocator for HybridObjects {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, allocator_api2::alloc::AllocError> {
        let ptr = unsafe { self.alloc(layout) };
        if ptr.is_null() {
            Err(allocator_api2::alloc::AllocError)
        } else {
            let slice = unsafe { std::slice::from_raw_parts_mut(ptr, layout.size()) };
            Ok(NonNull::from(slice))
        }
    }
    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        unsafe { self.dealloc(ptr.as_ptr(), layout) }
    }
}


